### ISSUE TITLE
屏幕分辨率改成1280*720后仍然显示修改分辨率

### ISSUE THREAD

**Issue by RicardoMLi** [FirstJavaMaster/AzurLaneScripts#8]

**Comment by RicardoMLi** [comment]
check_size函数里面output是个""，是检测不到我的屏幕分辨率么？

**Comment by RicardoMLi** [comment]
我用的是python3.6，应该没啥大问题吧

**Comment by RicardoMLi** [comment]
换成python3.7也没用啊，心累

**Comment by RicardoMLi** [comment]
ADB PATH >>>> F:\迅雷下载\AzurLaneScripts-master/adb/adb.exe
检测设备连接状态 >>> 127.0.0.1:5555 ...

设备列表：
127.0.0.1:5555
emulator-5554
设备已连接

error: device offline
屏幕分辨率: 
请将分辨率设置为 1280x720 (横向 平板模式)

**Comment by FirstJavaMaster** [comment]
这应该是因为设备状态离线了。问题还是在模拟器和ADB驱动上。可以试试下面的方法：

· 重启模拟器
· 如果模拟器已经自带了ADB，则可以尝试将脚本中adb文件夹的文件拷贝至模拟器自带ADB目录。注意备份原文件
· 在adb目录下打开cmd，执行 adb kill-server 后再执行 adb start-server，然后执行 adb devices 查看是否解决
· 重启电脑
· 换个模拟器

**Comment by RicardoMLi** [comment]
D:\Python3_7\python.exe F:/迅雷下载/AzurLaneScripts-master/Fight.py
ADB PATH >>>> F:\迅雷下载\AzurLaneScripts-master/adb/adb.exe
检测设备连接状态 >>> 127.0.0.1:21503 ...

设备列表：
127.0.0.1:21503
设备已连接

屏幕分辨率: Physical size: 1280x720
像素密度: Physical density: 192
系统类型: SM-G9350
系统版本: 5.1.1

[连发模式] 持续寻找目标关卡

Traceback (most recent call last):
  File "F:/迅雷下载/AzurLaneScripts-master/Fight.py", line 27, in <module>
    run()
  File "F:/迅雷下载/AzurLaneScripts-master/Fight.py", line 15, in run
    StageFight.fight_stage(target_stage_list)
  File "F:\迅雷下载\AzurLaneScripts-master\bin\StageFight.py", line 17, in fight_stage
    in_enemy = PageUtils.in_enemy_page()
  File "F:\迅雷下载\AzurLaneScripts-master\common\PageUtils.py", line 45, in in_enemy_page
    return AutoAdb().check('temp_images/page/in-enemy.png')
  File "F:\迅雷下载\AzurLaneScripts-master\common\AutoAdb.py", line 51, in check
    loc = self.get_location(*temp_rel_path_list)
  File "F:\迅雷下载\AzurLaneScripts-master\common\AutoAdb.py", line 39, in get_location
    res = cv2.matchTemplate(sp_gray, temp_gray, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'

换了个逍遥模拟器然后就成这样了。

**Comment by FirstJavaMaster** [comment]
不知道啊。。。我重新下载代码然后运行也没问题。要不试试在“不包含中文”的路径下运行试试看

**Comment by RicardoMLi** [comment]
我也想是不是可能包含中文路径了，然后我用逍遥模拟器打不开游戏，就卸载了，现在打算再换个模拟器

**Comment by FirstJavaMaster** [comment]
我用的就是逍遥模拟器，软件打开有时是有点慢。我刚更新了一下，处理了文件路径的问题，可以试试看



发自我的小米手机在 RicardoLee <notifications@github.com>，2020年4月20日 下午5:43写道：

我也想是不是可能包含中文路径了，然后我用逍遥模拟器打不开游戏，就卸载了，现在打算再换个模拟器



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/FirstJavaMaster/AzurLaneScripts/issues/8#issuecomment-616434432",

"url": "https://github.com/FirstJavaMaster/AzurLaneScripts/issues/8#issuecomment-616434432",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by RicardoMLi** [comment]
好的，谢谢大佬，下完游戏试试

**Comment by FirstJavaMaster** [comment]
嗨，不是大佬。只是个会用python的小白而已。
( ´◔ ‸◔`)

**Comment by RicardoMLi** [comment]
现在运行时没问题，但是在结算页面不能点击确定呀，而且我看在战斗时候控制台也输出  
寻找敌人 ... 
滑动页面。 累积次数: 9.
寻找敌人 ... 
滑动页面。 累积次数: 10.
寻找敌人 ... 
滑动页面。 累积次数: 11.
这样的

**Comment by RicardoMLi** [comment]
原来是我整容锁定了，所有才会一直输出。

**Comment by FirstJavaMaster** [comment]
我还没试过阵容锁定，明天会看看🤔



在 2020年4月20日 下午6:49，RicardoLee <notifications@github.com>写道：

原来是我整容锁定了，所有才会一直输出。



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/FirstJavaMaster/AzurLaneScripts/issues/8#issuecomment-616469705",

"url": "https://github.com/FirstJavaMaster/AzurLaneScripts/issues/8#issuecomment-616469705",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Happiness-in-Danger** [comment]
![图片](https://user-images.githubusercontent.com/45912561/79891015-e9904980-8432-11ea-8749-9eccdeb7352a.png)
刚刚看到这个问题，我也发了，进入战斗后就是疯狂的滑动战斗结束后还是这个，而且还有出现boss也不打boss，还是去打其他的。

**Comment by FirstJavaMaster** [comment]
> ![图片](https://user-images.githubusercontent.com/45912561/79891015-e9904980-8432-11ea-8749-9eccdeb7352a.png)
> 刚刚看到这个问题，我也发了，进入战斗后就是疯狂的滑动战斗结束后还是这个，而且还有出现boss也不打boss，还是去打其他的。

战斗后仍在滑动的问题之前（4月13日）已经修正过一次。下载最新的代码试试看。
Boss出现后会尝试切换到第二队伍（即支持道中队和boss队的设计），然后重新寻敌，此时由于视角发生了变化，因此可能先会发现非Boss。不过再遇到Boss后会直接和boss战斗。
